// account
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// message
export const SHIFT_MESSAGE = 'SHIFT_MESSAGE';
export const SHIFT_REDIRECT = 'SHIFT_REDIRECT';

export const NEW_DECK = 'NEW_DECK';

//battle
export const REQUEST_FIGHT_REQUEST = 'REQUEST_FIGHT_REQUEST';
export const REQUEST_FIGHT_SUCCESS = 'REQUEST_FIGHT_SUCCESS';
export const REQUEST_FIGHT_FAILURE = 'REQUEST_FIGHT_FAILURE‌';

export const PUT_CARD_REQUEST = 'PUT_CARD_REQUEST';
export const PUT_CARD_SUCCESS = 'PUT_CARD_SUCCESS';
export const PUT_CARD_FAILURE = 'PUT_CARD_FAILURE‌';

export const MOVE_REQUEST = 'MOVE_REQUEST';
export const MOVE_SUCCESS = 'MOVE_SUCCESS';
export const MOVE_FAILURE = 'MOVE_FAILURE‌';

export const MOVE_PLAYER = 'MOVE_PLAYER';
export const UPDATE_OTHER_PLAYERS = 'UPDATE_OTHER_PLAYERS';
export const GET_MAP_DATA_REQUEST = 'GET_MAP_DATA_REQUEST';
export const GET_MAP_DATA_SUCCESS = 'GET_MAP_DATA_SUCCESS';
export const GET_MAP_DATA_FAILURE = 'GET_MAP_DATA_FAILURE';

export const PLAYER_CARDS_REQUEST = 'PLAYER_CARDS_REQUEST';
export const PLAYER_CARDS_SUCCESS = 'PLAYER_CARDS_SUCCESS';
export const PLAYER_CARDS_FAILURE = 'PLAYER_CARDS_FAILURE‌';

export const GET_PLAYER_STATUS_REQUEST = 'GET_PLAYER_STATUS_REQUEST';
export const GET_PLAYER_STATUS_SUCCESS = 'GET_PLAYER_STATUS_SUCCESS';
export const GET_PLAYER_STATUS_FAILURE = 'GET_PLAYER_STATUS_FAILURE‌';

export const GET_PLAYERS_REQUEST = 'GET_PLAYERS_REQUEST';
export const GET_PLAYERS_SUCCESS = 'GET_PLAYERS_SUCCESS';
export const GET_PLAYERS_FAILURE = 'GET_PLAYERS_FAILURE‌';

export const GET_CIVILIZATIONS_DETAILS_REQUEST =
  'GET_CIVILIZATIONS_DETAILS_REQUEST';
export const GET_CIVILIZATIONS_DETAILS_SUCCESS =
  'GET_CIVILIZATIONS_DETAILS_SUCCESS';
export const GET_CIVILIZATIONS_DETAILS_FAILURE =
  'GET_CIVILIZATIONS_DETAILS_FAILURE‌';

export const GET_CIVILIZATIONS_CARDS_REQUEST =
  'GET_CIVILIZATIONS_CARDS_REQUEST';
export const GET_CIVILIZATIONS_CARDS_SUCCESS =
  'GET_CIVILIZATIONS_CARDS_SUCCESS';
export const GET_CIVILIZATIONS_CARDS_FAILURE =
  'GET_CIVILIZATIONS_CARDS_FAILURE‌';

export const FIGHT_WITH_CIVILIZATION_REQUEST =
  'FIGHT_WITH_CIVILIZATION_REQUEST';
export const FIGHT_WITH_CIVILIZATION_SUCCESS =
  'FIGHT_WITH_CIVILIZATION_SUCCESS';
export const FIGHT_WITH_CIVILIZATION_FAILURE =
  'FIGHT_WITH_CIVILIZATION_FAILURE‌';

export const UPGRADE_CIVILIZATION_REQUEST = 'UPGRADE_CIVILIZATION_REQUEST';
export const UPGRADE_CIVILIZATION_SUCCESS = 'UPGRADE_CIVILIZATION_SUCCESS';
export const UPGRADE_CIVILIZATION_FAILURE = 'UPGRADE_CIVILIZATION_FAILURE‌';

export const GET_NOTIFICATIONS_REQUEST = 'GET_NOTIFICATIONS_REQUEST';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAILURE = 'GET_NOTIFICATIONS_FAILURE‌';

export const GET_CARD_TYPES_REQUEST = 'GET_CARD_TYPES_REQUEST';
export const GET_CARD_TYPES_SUCCESS = 'GET_CARD_TYPES_SUCCESS';
export const GET_CARD_TYPES_FAILURE = 'GET_CARD_TYPES_FAILURE‌';

export const CIVIL_CARD_REQUEST = 'CIVIL_CARD_REQUEST';
export const CIVIL_CARD_SUCCESS = 'CIVIL_CARD_SUCCESS';
export const CIVIL_CARD_FAILURE = 'CIVIL_CARD_FAILURE‌';

// no need to do any thing we make another request after these ones
export const BUY_CARD_REQUEST = 'BUY_CARD_REQUEST';
export const BUY_CARD_SUCCESS = 'BUY_CARD_SUCCESS';
export const Buy_CARD_FAILURE = 'Buy_CARD_FAILURE';

export const SELL_CARD_REQUEST = 'SELL_CARD_REQUEST';
export const SELL_CARD_SUCCESS = 'SELL_CARD_SUCCESS';
export const SELL_CARD_FAILURE = 'SELL_CARD_FAILURE';

export const DISCARD_CARD_REQUEST = 'DISCARD_CARD_REQUEST';
export const DISCARD_CARD_SUCCESS = 'DISCARD_CARD_SUCCESS';
export const DISCARD_CARD_FAILURE = 'DISCARD_CARD_FAILURE';

export const PICKUP_CARD_REQUEST = 'PICKUP_CARD_REQUEST';
export const PICKUP_CARD_SUCCESS = 'PICKUP_CARD_SUCCESS';
export const PICKUP_CARD_FAILURE = 'PICKUP_CARD_FAILURE';

export const UPGRADE_CARD_REQUEST = 'UPGRADE_CARD_REQUEST';
export const UPGRADE_CARD_SUCCESS = 'UPGRADE_CARD_SUCCESS';
export const UPGRADE_CARD_FAILURE = 'UPGRADE_CARD_FAILURE';

export const GET_ANSWER_REQUEST = 'GET_ANSWER_REQUEST';
export const GET_ANSWER_SUCCESS = 'GET_ANSWER_SUCCESS';
export const GET_ANSWER_FAILURE = 'GET_ANSWER_FAILURE';

export const GET_QUESTION_REQUEST = 'GET_QUESTION_REQUEST';
export const GET_QUESTION_SUCCESS = 'GET_QUESTION_SUCCESS';
export const GET_QUESTION_FAILURE = 'GET_QUESTION_FAILURE';

export const UPLOAD_ANSWER_REQUEST = 'UPLOAD_ANSWER_REQUEST';
export const UPLOAD_ANSWER_SUCCESS = 'UPLOAD_ANSWER_SUCCESS';
export const UPLOAD_ANSWER_FAILURE = 'UPLOAD_ANSWER_FAILURE';
