// account
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// message
export const SHIFT_MESSAGE = 'SHIFT_MESSAGE';
export const SHIFT_REDIRECT = 'SHIFT_REDIRECT';

export const NEW_DECK = 'NEW_DECK';

//battle
export const REQUEST_FIGHT_REQUEST = 'REQUEST_FIGHT_REQUEST';
export const REQUEST_FIGHT_SUCCESS = 'REQUEST_FIGHT_SUCCESS';
export const REQUEST_FIGHT_FAILURE = 'REQUEST_FIGHT_FAILURE‌';

export const PUT_CARD_REQUEST = 'PUT_CARD_REQUEST';
export const PUT_CARD_SUCCESS = 'PUT_CARD_SUCCESS';
export const PUT_CARD_FAILURE = 'PUT_CARD_FAILURE‌';

export const MOVE_REQUEST = 'MOVE_REQUEST';
export const MOVE_SUCCESS = 'MOVE_SUCCESS';
export const MOVE_FAILURE = 'MOVE_FAILURE‌';

export const MOVE_PLAYER = 'MOVE_PLAYER';
export const UPDATE_OTHER_PLAYERS = 'UPDATE_OTHER_PLAYERS';
export const MAP_DATA_REQUEST = 'MAP_DATA_REQUEST';
export const MAP_DATA_SUCCESS = 'MAP_DATA_SUCCESS';
export const MAP_DATA_FAILURE = 'MAP_DATA_FAILURE';

export const PLAYER_CARD_REQUEST = 'PLAYER_CARD_REQUEST';
export const PLAYER_CARD_SUCCESS = 'PLAYER_CARD_SUCCESS';
export const PLAYER_CARD_FAILURE = 'PLAYER_CARD_FAILURE‌';

export const GET_PLAYER_STATUS_REQUEST = 'GET_PLAYER_STATUS_REQUEST';
export const GET_PLAYER_STATUS_SUCCESS = 'GET_PLAYER_STATUS_SUCCESS';
export const GET_PLAYER_STATUS_FAILURE = 'GET_PLAYER_STATUS_FAILURE‌';

export const GET_NOTIFICATIONS_REQUEST = 'GET_NOTIFICATIONS_REQUEST';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAILURE = 'GET_NOTIFICATIONS_FAILURE‌';

export const CARD_TYPES_REQUEST = 'CARD_TYPES_REQUEST';
export const CARD_TYPES_SUCCESS = 'CARD_TYPES_SUCCESS';
export const CARD_TYPES_FAILURE = 'CARD_TYPES_FAILURE‌';

export const CIVIL_CARD_REQUEST = 'CIVIL_CARD_REQUEST';
export const CIVIL_CARD_SUCCESS = 'CIVIL_CARD_SUCCESS';
export const CIVIL_CARD_FAILURE = 'CIVIL_CARD_FAILURE‌';

// no need to do any thing we make another request after these ones
export const BUY_CARD_REQUEST = 'BUY_CARD_REQUEST';
export const BUY_CARD_SUCCESS = 'BUY_CARD_SUCCESS';
export const Buy_CARD_FAILURE = 'Buy_CARD_FAILURE';

export const SELL_CARD_REQUEST = 'SELL_CARD_REQUEST';
export const SELL_CARD_SUCCESS = 'SELL_CARD_SUCCESS';
export const SELL_CARD_FAILURE = 'SELL_CARD_FAILURE';

export const DISCARD_CARD_REQUEST = 'DISCARD_CARD_REQUEST';
export const DISCARD_CARD_SUCCESS = 'DISCARD_CARD_SUCCESS';
export const DISCARD_CARD_FAILURE = 'DISCARD_CARD_FAILURE';

export const PICKUP_CARD_REQUEST = 'PICKUP_CARD_REQUEST';
export const PICKUP_CARD_SUCCESS = 'PICKUP_CARD_SUCCESS';
export const PICKUP_CARD_FAILURE = 'PICKUP_CARD_FAILURE';
